// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiGXBkCB8M9taLDgvzqdt-piIEB4gY2Y',
    appId: '1:412155959836:web:4dac0ae612283a100a9dd9',
    messagingSenderId: '412155959836',
    projectId: 'helpdatabase-6c6d0',
    authDomain: 'helpdatabase-6c6d0.firebaseapp.com',
    storageBucket: 'helpdatabase-6c6d0.firebasestorage.app',
    measurementId: 'G-J7DZPG00HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz4xqs0F8t43c37_kh4Qw6i_WxWxky1lg',
    appId: '1:412155959836:android:29c2cc53e87ce3710a9dd9',
    messagingSenderId: '412155959836',
    projectId: 'helpdatabase-6c6d0',
    storageBucket: 'helpdatabase-6c6d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAxGQYiUxX1Z1wSROjN_AKekSr3Cl4H48',
    appId: '1:412155959836:ios:cd56f5359ce5d6a40a9dd9',
    messagingSenderId: '412155959836',
    projectId: 'helpdatabase-6c6d0',
    storageBucket: 'helpdatabase-6c6d0.firebasestorage.app',
    iosClientId: '412155959836-egopgppejrfph7p8luceevj850mjc7id.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAxGQYiUxX1Z1wSROjN_AKekSr3Cl4H48',
    appId: '1:412155959836:ios:cd56f5359ce5d6a40a9dd9',
    messagingSenderId: '412155959836',
    projectId: 'helpdatabase-6c6d0',
    storageBucket: 'helpdatabase-6c6d0.firebasestorage.app',
    iosClientId: '412155959836-egopgppejrfph7p8luceevj850mjc7id.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaiGXBkCB8M9taLDgvzqdt-piIEB4gY2Y',
    appId: '1:412155959836:web:9a1e4c6622490fb30a9dd9',
    messagingSenderId: '412155959836',
    projectId: 'helpdatabase-6c6d0',
    authDomain: 'helpdatabase-6c6d0.firebaseapp.com',
    storageBucket: 'helpdatabase-6c6d0.firebasestorage.app',
    measurementId: 'G-5K9MD6MSTZ',
  );
}
